//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  blip: Blip;
  blipConnection: BlipConnection;
  post: Post;
  postConnection: PostConnection;
  review: Review;
  reviewConnection: ReviewConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlipArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlipConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlipFilter>;
};


export type QueryPostArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostFilter>;
};


export type QueryReviewArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryReviewConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ReviewFilter>;
};

export type DocumentFilter = {
  blip?: InputMaybe<BlipFilter>;
  post?: InputMaybe<PostFilter>;
  review?: InputMaybe<ReviewFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Blip | Post | Review | Folder;

export type Blip = Node & Document & {
  __typename?: 'Blip';
  title: Scalars['String']['output'];
  pubDate: Scalars['String']['output'];
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type BlipFilter = {
  title?: InputMaybe<StringFilter>;
  pubDate?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BlipConnectionEdges = {
  __typename?: 'BlipConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Blip>;
};

export type BlipConnection = Connection & {
  __typename?: 'BlipConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BlipConnectionEdges>>>;
};

export type Post = Node & Document & {
  __typename?: 'Post';
  title: Scalars['String']['output'];
  pubDate: Scalars['String']['output'];
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  summary: Scalars['String']['output'];
  socialImageFilename: Scalars['String']['output'];
  cloudinaryThumb: Scalars['String']['output'];
  thumb: Scalars['String']['output'];
  thumbAlt: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PostFilter = {
  title?: InputMaybe<StringFilter>;
  pubDate?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  socialImageFilename?: InputMaybe<StringFilter>;
  cloudinaryThumb?: InputMaybe<StringFilter>;
  thumb?: InputMaybe<StringFilter>;
  thumbAlt?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PostConnectionEdges = {
  __typename?: 'PostConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Post>;
};

export type PostConnection = Connection & {
  __typename?: 'PostConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PostConnectionEdges>>>;
};

export type Review = Node & Document & {
  __typename?: 'Review';
  title: Scalars['String']['output'];
  pubDate: Scalars['String']['output'];
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  description: Scalars['String']['output'];
  address: Scalars['String']['output'];
  city: Scalars['String']['output'];
  state?: Maybe<Scalars['String']['output']>;
  country: Scalars['String']['output'];
  coordinates: Scalars['String']['output'];
  infoUrl: Scalars['String']['output'];
  heroImageAlt: Scalars['String']['output'];
  heroImage: Scalars['String']['output'];
  heroImageAttribution?: Maybe<Scalars['String']['output']>;
  heroImageUrl?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ReviewFilter = {
  title?: InputMaybe<StringFilter>;
  pubDate?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  city?: InputMaybe<StringFilter>;
  state?: InputMaybe<StringFilter>;
  country?: InputMaybe<StringFilter>;
  coordinates?: InputMaybe<StringFilter>;
  infoUrl?: InputMaybe<StringFilter>;
  heroImageAlt?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<StringFilter>;
  heroImageAttribution?: InputMaybe<StringFilter>;
  heroImageUrl?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ReviewConnectionEdges = {
  __typename?: 'ReviewConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Review>;
};

export type ReviewConnection = Connection & {
  __typename?: 'ReviewConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ReviewConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateBlip: Blip;
  createBlip: Blip;
  updatePost: Post;
  createPost: Post;
  updateReview: Review;
  createReview: Review;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateBlipArgs = {
  relativePath: Scalars['String']['input'];
  params: BlipMutation;
};


export type MutationCreateBlipArgs = {
  relativePath: Scalars['String']['input'];
  params: BlipMutation;
};


export type MutationUpdatePostArgs = {
  relativePath: Scalars['String']['input'];
  params: PostMutation;
};


export type MutationCreatePostArgs = {
  relativePath: Scalars['String']['input'];
  params: PostMutation;
};


export type MutationUpdateReviewArgs = {
  relativePath: Scalars['String']['input'];
  params: ReviewMutation;
};


export type MutationCreateReviewArgs = {
  relativePath: Scalars['String']['input'];
  params: ReviewMutation;
};

export type DocumentUpdateMutation = {
  blip?: InputMaybe<BlipMutation>;
  post?: InputMaybe<PostMutation>;
  review?: InputMaybe<ReviewMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  blip?: InputMaybe<BlipMutation>;
  post?: InputMaybe<PostMutation>;
  review?: InputMaybe<ReviewMutation>;
};

export type BlipMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  pubDate?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PostMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  pubDate?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  summary?: InputMaybe<Scalars['String']['input']>;
  socialImageFilename?: InputMaybe<Scalars['String']['input']>;
  cloudinaryThumb?: InputMaybe<Scalars['String']['input']>;
  thumb?: InputMaybe<Scalars['String']['input']>;
  thumbAlt?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ReviewMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  pubDate?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  description?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  city?: InputMaybe<Scalars['String']['input']>;
  state?: InputMaybe<Scalars['String']['input']>;
  country?: InputMaybe<Scalars['String']['input']>;
  coordinates?: InputMaybe<Scalars['String']['input']>;
  infoUrl?: InputMaybe<Scalars['String']['input']>;
  heroImageAlt?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  heroImageAttribution?: InputMaybe<Scalars['String']['input']>;
  heroImageUrl?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type BlipPartsFragment = { __typename: 'Blip', title: string, pubDate: string, tags?: Array<string | null> | null, body?: any | null };

export type PostPartsFragment = { __typename: 'Post', title: string, pubDate: string, tags?: Array<string | null> | null, summary: string, socialImageFilename: string, cloudinaryThumb: string, thumb: string, thumbAlt: string, body?: any | null };

export type ReviewPartsFragment = { __typename: 'Review', title: string, pubDate: string, tags?: Array<string | null> | null, description: string, address: string, city: string, state?: string | null, country: string, coordinates: string, infoUrl: string, heroImageAlt: string, heroImage: string, heroImageAttribution?: string | null, heroImageUrl?: string | null, body?: any | null };

export type BlipQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BlipQuery = { __typename?: 'Query', blip: { __typename: 'Blip', id: string, title: string, pubDate: string, tags?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BlipConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlipFilter>;
}>;


export type BlipConnectionQuery = { __typename?: 'Query', blipConnection: { __typename?: 'BlipConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BlipConnectionEdges', cursor: string, node?: { __typename: 'Blip', id: string, title: string, pubDate: string, tags?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PostQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PostQuery = { __typename?: 'Query', post: { __typename: 'Post', id: string, title: string, pubDate: string, tags?: Array<string | null> | null, summary: string, socialImageFilename: string, cloudinaryThumb: string, thumb: string, thumbAlt: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PostConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostFilter>;
}>;


export type PostConnectionQuery = { __typename?: 'Query', postConnection: { __typename?: 'PostConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PostConnectionEdges', cursor: string, node?: { __typename: 'Post', id: string, title: string, pubDate: string, tags?: Array<string | null> | null, summary: string, socialImageFilename: string, cloudinaryThumb: string, thumb: string, thumbAlt: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ReviewQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ReviewQuery = { __typename?: 'Query', review: { __typename: 'Review', id: string, title: string, pubDate: string, tags?: Array<string | null> | null, description: string, address: string, city: string, state?: string | null, country: string, coordinates: string, infoUrl: string, heroImageAlt: string, heroImage: string, heroImageAttribution?: string | null, heroImageUrl?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ReviewConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ReviewFilter>;
}>;


export type ReviewConnectionQuery = { __typename?: 'Query', reviewConnection: { __typename?: 'ReviewConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ReviewConnectionEdges', cursor: string, node?: { __typename: 'Review', id: string, title: string, pubDate: string, tags?: Array<string | null> | null, description: string, address: string, city: string, state?: string | null, country: string, coordinates: string, infoUrl: string, heroImageAlt: string, heroImage: string, heroImageAttribution?: string | null, heroImageUrl?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const BlipPartsFragmentDoc = gql`
    fragment BlipParts on Blip {
  __typename
  title
  pubDate
  tags
  body
}
    `;
export const PostPartsFragmentDoc = gql`
    fragment PostParts on Post {
  __typename
  title
  pubDate
  tags
  summary
  socialImageFilename
  cloudinaryThumb
  thumb
  thumbAlt
  body
}
    `;
export const ReviewPartsFragmentDoc = gql`
    fragment ReviewParts on Review {
  __typename
  title
  pubDate
  tags
  description
  address
  city
  state
  country
  coordinates
  infoUrl
  heroImageAlt
  heroImage
  heroImageAttribution
  heroImageUrl
  body
}
    `;
export const BlipDocument = gql`
    query blip($relativePath: String!) {
  blip(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BlipParts
  }
}
    ${BlipPartsFragmentDoc}`;
export const BlipConnectionDocument = gql`
    query blipConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BlipFilter) {
  blipConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BlipParts
      }
    }
  }
}
    ${BlipPartsFragmentDoc}`;
export const PostDocument = gql`
    query post($relativePath: String!) {
  post(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PostParts
  }
}
    ${PostPartsFragmentDoc}`;
export const PostConnectionDocument = gql`
    query postConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PostFilter) {
  postConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PostParts
      }
    }
  }
}
    ${PostPartsFragmentDoc}`;
export const ReviewDocument = gql`
    query review($relativePath: String!) {
  review(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ReviewParts
  }
}
    ${ReviewPartsFragmentDoc}`;
export const ReviewConnectionDocument = gql`
    query reviewConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ReviewFilter) {
  reviewConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ReviewParts
      }
    }
  }
}
    ${ReviewPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      blip(variables: BlipQueryVariables, options?: C): Promise<{data: BlipQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlipQueryVariables, query: string}> {
        return requester<{data: BlipQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlipQueryVariables, query: string}, BlipQueryVariables>(BlipDocument, variables, options);
      },
    blipConnection(variables?: BlipConnectionQueryVariables, options?: C): Promise<{data: BlipConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlipConnectionQueryVariables, query: string}> {
        return requester<{data: BlipConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlipConnectionQueryVariables, query: string}, BlipConnectionQueryVariables>(BlipConnectionDocument, variables, options);
      },
    post(variables: PostQueryVariables, options?: C): Promise<{data: PostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostQueryVariables, query: string}> {
        return requester<{data: PostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostQueryVariables, query: string}, PostQueryVariables>(PostDocument, variables, options);
      },
    postConnection(variables?: PostConnectionQueryVariables, options?: C): Promise<{data: PostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostConnectionQueryVariables, query: string}> {
        return requester<{data: PostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostConnectionQueryVariables, query: string}, PostConnectionQueryVariables>(PostConnectionDocument, variables, options);
      },
    review(variables: ReviewQueryVariables, options?: C): Promise<{data: ReviewQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReviewQueryVariables, query: string}> {
        return requester<{data: ReviewQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReviewQueryVariables, query: string}, ReviewQueryVariables>(ReviewDocument, variables, options);
      },
    reviewConnection(variables?: ReviewConnectionQueryVariables, options?: C): Promise<{data: ReviewConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReviewConnectionQueryVariables, query: string}> {
        return requester<{data: ReviewConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ReviewConnectionQueryVariables, query: string}, ReviewConnectionQueryVariables>(ReviewConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  