// Auto-generated by scripts/sync-obsidian-library.mjs — do not edit manually

export interface LibraryLink {
  title: string
  url: string
  description?: string
  created: string
}

export const libraryLinks: LibraryLink[] = [
  {
    title: "The ultimate guide to /goal",
    url: "https://x.com/Saboo_Shubham_/status/2054988166541770782",
    description: "/goal is not a feature. It is a primitive. HTTP is a primitive. JSON is a primitive. /goal is becoming one for coding agents.A few weeks ago...",
    created: "2026-05-15",
  },
  {
    title: "Agent view in Claude Code",
    url: "https://claude.com/blog/agent-view-in-claude-code?utm_source=substack&utm_medium=email",
    description: "Today we're introducing agent view in Claude Code: one place to manage all your Claude Code sessions.",
    created: "2026-05-12",
  },
  {
    title: "The Main Path to Truly Creative AI",
    url: "https://danielmiessler.com/blog/the-main-path-to-truly-creative-ai",
    description: "Why real creativity might require real feeling — and what we'd owe an AI that had it",
    created: "2026-05-12",
  },
  {
    title: "The Organization Is the Bottleneck",
    url: "https://www.oreilly.com/radar/the-organization-is-the-bottleneck/?ref=sidebar",
    description: "Everyone is adopting AI coding tools. Engineers are writing code faster than ever. But are organizations actually delivering value faster? That’s not",
    created: "2026-05-12",
  },
  {
    title: "The unreasonable effectiveness of HTML",
    url: "https://thariqs.github.io/html-effectiveness/?ref=sidebar",
    created: "2026-05-12",
  },
  {
    title: "lyogavin/airllm: AirLLM 70B inference with single 4GB GPU",
    url: "https://github.com/lyogavin/airllm?utm_source=www.simplifyingcomplexity.tech&utm_medium=newsletter&utm_campaign=ai-weekly-recap-week-20&_bhlid=ee7253acd8936ad516133e0c4fc7955f51d06a22",
    description: "AirLLM 70B inference with single 4GB GPU. Contribute to lyogavin/airllm development by creating an account on GitHub.",
    created: "2026-05-12",
  },
  {
    title: "Datatype — variable font that turns text into charts",
    url: "https://franktisellano.github.io/datatype/?ck_subscriber_id=1665201471",
    description: "An OpenType variable font that turns simple text expressions into inline charts. No JavaScript, no images — just type.",
    created: "2026-05-10",
  },
  {
    title: "DESIGN.md Explained - The Format Reshaping How AI Builds UI",
    url: "https://departmentofproduct.substack.com/p/designmd-explained-the-format-reshaping?utm_source=unicornclub.dev&ref=unicornclub.dev",
    description: "Google has open-sourced the spec. What is DESIGN.md and why should product teams care?",
    created: "2026-05-07",
  },
]
