// Auto-generated by scripts/sync-obsidian-library.mjs — do not edit manually

export interface LibraryLink {
  title: string
  url: string
  description?: string
  created: string
}

export const libraryLinks: LibraryLink[] = [
  {
    title: "Better fluid sizing with round()",
    url: "https://ishadeed.com/article/css-round/",
    description: "Using the round() function to get a more predictable fluid sizing.",
    created: "2026-06-13",
  },
  {
    title: "Coding is solved? Software is not.",
    url: "https://arcplane.ai/journal/software-is-not-solved",
    description: "If coding is becoming solved, why does software still feel hard? A look at what AI agents change, and what they leave behind.",
    created: "2026-06-13",
  },
  {
    title: "Nudges, Biases & Heuristics for the Age of AI",
    url: "https://www.nudges.fyi/",
    description: "45 interactive field cards covering nudges, biases, heuristics, and AI phenomena. A practical reference for designers, researchers, and product teams building with AI.",
    created: "2026-06-13",
  },
  {
    title: "boneyard - skeleton screens for your UI",
    url: "https://boneyard.vercel.app/overview?ref=sidebar",
    description: "Pixel-perfect skeleton loading screens auto-extracted from your real DOM. Zero configuration, zero layout shift.",
    created: "2026-06-13",
  },
  {
    title: "Discovery vs Delivery",
    url: "https://buzzusborne.com/writing/discovery-delivery/?ref=sidebar",
    description: "Buzz is a product design leader with over 18 years of experience building products and teams.",
    created: "2026-06-11",
  },
  {
    title: "Evolving from designers to builders",
    url: "https://gusto.com/company-news/designers-to-builders",
    description: "In the Gusto Design org, we just went through one of the biggest shifts that any of us have seen in our careers: we transformed from a traditional design team to an “AI-native” one within a quarter and are now benchmarking ahead of the industry.",
    created: "2026-06-11",
  },
  {
    title: "UI Skills for Design Engineers | Curated Skill Directory",
    url: "https://www.ui-skills.com/?ref=sidebar",
    description: "Discover curated UI Skills for design engineers, including accessibility, motion, frontend craft, and interface quality guides with copy-ready install commands.",
    created: "2026-06-11",
  },
  {
    title: "What a good website does.",
    url: "https://specification.website/?ref=sidebar",
    description: "A platform-agnostic, full specification of the technical features a good website should have. Built in the open under an MIT licence.",
    created: "2026-06-11",
  },
  {
    title: "A few ways of specifying per-theme colours in only CSS",
    url: "https://chrismorgan.info/css-themed-colours",
    description: "They are: ① write it all out; ② use palette variables; ③ the space toggle hack; ④ color-mix(); ⑤ light-dark(); ⑥ if(); ⑦ paused @keyframes animation",
    created: "2026-06-07",
  },
  {
    title: "Callout UI with CSS Offset & Border",
    url: "https://frontendmasters.com/blog/callout-ui-with-css-offset-border/",
    description: "We look at designing callout UI elements using CSS, incorporating leader lines and text boxes. It details setting up the HTML structure, utilizing CSS properties like offset-path and borders.",
    created: "2026-06-07",
  },
  {
    title: "How Claude Code’s lead designer builds with AI",
    url: "https://www.youtube.com/watch?v=hKeDfupbA4U",
    description: "During Dive Club Live in NYC we got to hear from Claude Code’s lead designer, Meaghan Choi. She shared a demo of how the team at Anthropic uses Claude Code a...",
    created: "2026-06-05",
  },
  {
    title: "Build a brand you're proud of, in minutes",
    url: "https://branda.co/?via=toools#pricing",
    description: "Branda turns a one-sentence idea into a full brand — strategy, name, logo, palette, type, and a brand kit. 200 free credits on signup.",
    created: "2026-06-04",
  },
  {
    title: "Cynicism is a luxury; hope is a necessity.",
    url: "https://www.chrbutler.com/cynicism-is-a-luxury-hope-is-a-necessity?ref=sidebar",
    description: "One’s ability to ignore politics is a product of functional system that shares your worldview.",
    created: "2026-06-04",
  },
  {
    title: "Essential transitions for web apps",
    url: "https://transitions.dev/?ref=sidebar",
    description: "Collection of the most essential transitions for web apps that you can just copy and paste into any project.",
    created: "2026-06-04",
  },
  {
    title: "Post by @DJ_CURFEW on X",
    url: "https://x.com/dj_curfew/status/2057522382315929802?s=12",
    description: "Today we reduced headcount by 22%. The business is the strongest it's ever been. So I think it's important to be direct about what I'm seein",
    created: "2026-06-04",
  },
  {
    title: "The Speed of Prototyping in the Age of AI",
    url: "https://darylcecile.net/notes/speed-of-prototyping-age-of-ai?ref=sidebar",
    description: "How AI has changed the way I prototype, plan, and ship; and what I'm doing to keep my hands dirty.",
    created: "2026-06-04",
  },
  {
    title: "Tools the Vercel Product Design Team Actually Uses",
    url: "https://www.hannahhearth.com/posts/tools-the-vercel-product-design-team-actually-uses",
    description: "A blog about design leadership",
    created: "2026-06-04",
  },
  {
    title: "Vocabulary",
    url: "https://animations.dev/vocabulary?ref=sidebar",
    description: "A glossary of common animation patterns, so you know what to ask for.",
    created: "2026-06-04",
  },
  {
    title: "heerich.js",
    url: "https://meodai.github.io/heerich/?ref=sidebar#spheres",
    description: "A tiny engine for 3D voxel scenes rendered to SVG. Boolean ops, oblique/perspective cameras, zero dependencies. Inspired by the geometric cardboard sculptures of Erwin Heerich.",
    created: "2026-06-04",
  },
  {
    title: "A harness for every task: dynamic workflows in Claude Code",
    url: "https://x.com/trq212/status/2061907337154367865",
    description: "Last week, we released dynamic workflows in Claude Code. Claude can now write its own harness on the fly, custom-built for the task at hand....",
    created: "2026-06-03",
  },
  {
    title: "X posts as clean Markdown for LLMs",
    url: "https://tweet.md/?ref=producthunt",
    description: "Get any X post or thread as clean Markdown for LLMs, agents, and research. Swap x.com for tweet.md or use the API.",
    created: "2026-05-27",
  },
  {
    title: "obra/superpowers: An agentic skills framework & software development methodology that works.",
    url: "https://github.com/obra/superpowers",
    description: "An agentic skills framework & software development methodology that works. - obra/superpowers",
    created: "2026-05-27",
  },
  {
    title: "After Automation",
    url: "https://every.to/p/after-automation?utm_source=www.gethalfbaked.com&utm_medium=newsletter&utm_campaign=half-baked-615-social-recruiting-aida-framework&_bhlid=8c31bdd039537dec0f63067c3a0693e285d5cc86",
    description: "AI progress creates more work for humans, not less",
    created: "2026-05-23",
  },
  {
    title: "Better Experiments with LLM Evals — A funnel, not a fork",
    url: "https://engineering.atspotify.com/2026/5/better-experiments-with-llm-evals-a-funnel-not-a-fork?utm_source=tldrai",
    description: "TL;DR  LLM evals, automated judges that assess relevance, coherence, and quality at scale, are a powerful new tool. Paired with online experiments, they raise the hit rate of what we test and create a feedback loop that makes both evals and experiments smarter over time.",
    created: "2026-05-23",
  },
  {
    title: "Why I Left Product Management to Build More",
    url: "https://www.noahzender.com/why-i-left-product-management",
    description: "Why I Left Product Management to Build More — an essay by Noah Zender",
    created: "2026-05-23",
  },
  {
    title: "The Workflow Collision",
    url: "https://webframp.com/posts/the-workflow-collision/?ref=sidebar",
    description: "Your team's workflow and your agent's lifecycle want different things",
    created: "2026-05-22",
  },
  {
    title: "Train Your Judgement",
    url: "https://emilkowal.ski/ui/train-your-judgement",
    description: "Settling for good enough is not good enough.",
    created: "2026-05-22",
  },
  {
    title: "Hermes just got 10x better...",
    url: "https://www.youtube.com/watch?v=8iZUyE7SlXo",
    description: "Here are 8 new Hermes Agent features that makes it SO much more powerful2nd Youtube Channel:  https://youtube.com/@AlexFinnLabsOfficialFULL Hermes Agent bootcamp in the Vibe Coding Academy coming u",
    created: "2026-05-19",
  },
  {
    title: "AGENTMEMORY — PERSISTENT MEMORY FOR AI CODING AGENTS",
    url: "https://www.agent-memory.dev/?utm_source=www.simplifyingcomplexity.tech&utm_medium=newsletter&utm_campaign=ai-weekly-recap-week-21&_bhlid=94c19a84599ec0c1a3df97689a46e167a3130d37",
    description: "The memory layer your coding agent should have had from day one. 95.2% retrieval R@5. 92% fewer tokens. 0 external databases. Works with every agent.",
    created: "2026-05-17",
  },
  {
    title: "When Sites Need to Walk Away",
    url: "https://chriscoyier.net/2026/04/28/when-sites-need-to-walk-away/?ref=sidebar",
    description: "The Internet Archive has a new book: VANISHING CULTURE. (Digital copy is free.) According to a Pew Research Center report, 26% of pages from 2013-2023 are no longer accessible. But that’s not the whole story. In a new study published in Internet Archive's book, VANISHING CULTURE, data scientists working with the Wayback Machine have found:…",
    created: "2026-05-16",
  },
  {
    title: "Frontend isn't Dead. Your Focus Needs to Change.",
    url: "https://formation.dev/blog/frontend-isnt-dead-but-your-focus-needs-to-change/",
    description: "Frontend development isn’t dead, but AI is changing the role. Learn where AI helps, where it struggles, and where frontend engineers should focus.",
    created: "2026-05-15",
  },
  {
    title: "Pilcrow ¶ — make your clanker your editor",
    url: "https://pilcrow.ink/",
    description: "Make your clanker your editor. A prose linter plus interpretive lenses anchored in classical style guides. AI-tell detection is one feature among many.",
    created: "2026-05-15",
  },
  {
    title: "The ultimate guide to /goal",
    url: "https://x.com/Saboo_Shubham_/status/2054988166541770782",
    description: "/goal is not a feature. It is a primitive. HTTP is a primitive. JSON is a primitive. /goal is becoming one for coding agents.A few weeks ago...",
    created: "2026-05-15",
  },
  {
    title: "Agent view in Claude Code",
    url: "https://claude.com/blog/agent-view-in-claude-code?utm_source=substack&utm_medium=email",
    description: "Today we're introducing agent view in Claude Code: one place to manage all your Claude Code sessions.",
    created: "2026-05-12",
  },
  {
    title: "Inside Anthropic’s 2026 Developer Conference",
    url: "https://every.to/chain-of-thought/inside-anthropic-s-2026-developer-conference",
    description: "What it was like in the room, plus what the new Managed Agents features look like in production",
    created: "2026-05-12",
  },
  {
    title: "Learn AI Layer by Layer",
    url: "https://learnai.robennals.org/?utm_source=substack&utm_medium=email",
    description: "An interactive, visual guide to understanding AI from first principles. Learn neural networks, transformers, and modern AI through hands-on experimentation.",
    created: "2026-05-12",
  },
  {
    title: "The Main Path to Truly Creative AI",
    url: "https://danielmiessler.com/blog/the-main-path-to-truly-creative-ai",
    description: "Why real creativity might require real feeling — and what we'd owe an AI that had it",
    created: "2026-05-12",
  },
  {
    title: "The Organization Is the Bottleneck",
    url: "https://www.oreilly.com/radar/the-organization-is-the-bottleneck/?ref=sidebar",
    description: "Everyone is adopting AI coding tools. Engineers are writing code faster than ever. But are organizations actually delivering value faster? That’s not",
    created: "2026-05-12",
  },
  {
    title: "The unreasonable effectiveness of HTML",
    url: "https://thariqs.github.io/html-effectiveness/?ref=sidebar",
    created: "2026-05-12",
  },
  {
    title: "lyogavin/airllm: AirLLM 70B inference with single 4GB GPU",
    url: "https://github.com/lyogavin/airllm?utm_source=www.simplifyingcomplexity.tech&utm_medium=newsletter&utm_campaign=ai-weekly-recap-week-20&_bhlid=ee7253acd8936ad516133e0c4fc7955f51d06a22",
    description: "AirLLM 70B inference with single 4GB GPU. Contribute to lyogavin/airllm development by creating an account on GitHub.",
    created: "2026-05-12",
  },
  {
    title: "Datatype — variable font that turns text into charts",
    url: "https://franktisellano.github.io/datatype/?ck_subscriber_id=1665201471",
    description: "An OpenType variable font that turns simple text expressions into inline charts. No JavaScript, no images — just type.",
    created: "2026-05-10",
  },
  {
    title: "DESIGN.md Explained - The Format Reshaping How AI Builds UI",
    url: "https://departmentofproduct.substack.com/p/designmd-explained-the-format-reshaping?utm_source=unicornclub.dev&ref=unicornclub.dev",
    description: "Google has open-sourced the spec. What is DESIGN.md and why should product teams care?",
    created: "2026-05-07",
  },
]
